---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/docker"
    schedule:
      interval: "monthly"
    groups:
      docker-compose:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      python-production:
        dependency-type: "production"
        exclude-patterns:
          - "flask-*"
      python-dev:
        dependency-type: "development"
        exclude-patterns:
          - "flask-*"
      flask:
        patterns:
          - "flask-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gh-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm-production:
        dependency-type: "production"
      npm-dev:
        dependency-type: "development"
