repos:
  - repo: https://github.com/psf/black
    rev: '21.6b0'
    hooks:
      - id: black
        exclude: '^(data/)'
        args: ['--check']

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        exclude: '^(data/)'

  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args: ['--profile', 'black', '--check-only']
