"""Change name and original_name types to Path

Revision ID: 3dfa0778a309
Revises: eed310013915
Create Date: 2025-04-04 12:09:42.437767

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3dfa0778a309"
down_revision = "eed310013915"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "original_name",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.Text(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "original_name",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
