"""Require file hashes be unique

Revision ID: 57ede73a71b8
Revises: 66f8a8ea21a9
Create Date: 2025-04-03 23:16:27.602286

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "57ede73a71b8"
down_revision = "66f8a8ea21a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index("ix_uploads_file_hash")
        batch_op.create_index(
            batch_op.f("ix_uploads_file_hash"), ["file_hash"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_file_hash"))
        batch_op.create_index("ix_uploads_file_hash", ["file_hash"], unique=False)

    # ### end Alembic commands ###
