"""Add uploads table

Revision ID: 66f8a8ea21a9
Revises:
Create Date: 2025-04-03 17:46:14.494089

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "66f8a8ea21a9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mimetype", sa.String(length=128), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_uploads_file_hash"), ["file_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_uploads_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_uploads_url"), ["url"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_url"))
        batch_op.drop_index(batch_op.f("ix_uploads_name"))
        batch_op.drop_index(batch_op.f("ix_uploads_file_hash"))

    op.drop_table("uploads")
    # ### end Alembic commands ###
