"""Make mimetype non-nullable, remove index on original_name

Revision ID: b0f653a2f1a0
Revises: 3dfa0778a309
Create Date: 2025-04-04 14:53:18.835264

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b0f653a2f1a0"
down_revision = "3dfa0778a309"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "mimetype", existing_type=sa.VARCHAR(length=128), nullable=False
        )
        batch_op.drop_index("ix_uploads_original_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index(
            "ix_uploads_original_name", ["original_name"], unique=False
        )
        batch_op.alter_column(
            "mimetype", existing_type=sa.VARCHAR(length=128), nullable=True
        )

    # ### end Alembic commands ###
