"""Rename name and url columns

Revision ID: eed310013915
Revises: 57ede73a71b8
Create Date: 2025-04-03 23:41:40.469904

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "eed310013915"
down_revision = "57ede73a71b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column("name", new_column_name="original_name")
        batch_op.alter_column("url", new_column_name="name")

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_url"))
        batch_op.drop_index(batch_op.f("ix_uploads_name"))
        batch_op.create_index(
            batch_op.f("ix_uploads_original_name"), ["original_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_uploads_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.alter_column("name", new_column_name="url")
        batch_op.alter_column("original_name", new_column_name="name")

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_name"))
        batch_op.drop_index(batch_op.f("ix_uploads_original_name"))
        batch_op.create_index(batch_op.f("ix_uploads_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_uploads_url"), ["url"], unique=True)

    # ### end Alembic commands ###
