name: rehome

services:
  rehome:
    container_name: rehome
    restart: "no"
    init: true
    read_only: true
    user: ${PUID:-1000}:${PGID:-1000}
    env_file: .env
    environment:
      CFG_SECRET_KEY: ${CFG_SECRET_KEY:?}
    volumes:
      - ${BASE_DIR:-.}/config/app:/config
      - ${BASE_DIR:-.}/data/app:/data
      - ../:/app
    tmpfs:
      - /tmp
    networks:
      - rehome
    ports:
      - "5000:5000"
    build:
      context: ../
      target: development
    deploy:
      resources:
        limits:
          cpus: ${REHOME_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${REHOME_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  rehome:
