#!/command/with-contenv sh
set -eu

if ! test -f "$SETTINGS_FILE_FOR_DYNACONF"; then
    echo "Copying default settings.yml"
    s6-setuidgid "$PUID:$PGID" cp -u "/app/$FLASK_APP/resources/config/settings.yml" "$SETTINGS_FILE_FOR_DYNACONF"
fi
