#!/command/with-contenv sh
set -eu

cd /app || exit 1

if test -d "$PATHS_STATIC/.webassets-cache"; then
    s6-setuidgid "$PUID:$PGID" flask assets clean
fi

s6-setuidgid "$PUID:$PGID" flask assets build
