##
## Configuration can be done here or via env vars.
## Env var usage is documented here: https://www.dynaconf.com/envvars/
## Env var prefix is set to 'CFG_', not 'DYNACONF_'.
##

## Required
# https://flask.palletsprojects.com/en/stable/config/#SECRET_KEY
secret_key = ""

[nav_links]
somesite = "https://somesite.com"
anothersite = "https://anothersite.com"

[auth]
token = ""

[uploads]
name_length = 5
use_x_accel_redirect = false

[gravatar]
email = ""

[sentry]
dsn = ""
