##
## Configuration can be done here or via env vars.
## Env var usage is documented here: https://www.dynaconf.com/envvars/
## Env var prefix is set to 'CFG_', not 'DYNACONF_'.
##

[home.links.default]
somesite = "https://somesite.com"
anothersite = "https://anothersite.com"

[gravatar]
email = ""

[uploads]
min_url_length = 3
upload_token = ""
use_x_accel_redirect = false
display_inline = [
    "txt",
    "php",
    "rb",
    "sh",
    "py",
    "conf",
    "c",
    "cpp",
    "java",
    "rs",
    "html",
    "htm",
    "js",
    "xml",
    "sql",
    "lua",
    "cs",
    "pl",
    "md",
    "ini",
    "shtml",
    "yaml",
    "cfg",
    "go",
    "fish",
    "yml",
    "bash",
]
