name: Create and publish a Docker image on base image updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for base image updates
        id: updatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/python:latest
          image: ${{ env.IMAGE_NAME }}:main

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: steps.updatecheck.outputs.needs-updating == 'true'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        if: steps.updatecheck.outputs.needs-updating == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        if: steps.updatecheck.outputs.needs-updating == 'true'
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
