---
name: "Lint"

on: # yamllint disable-line rule:truthy
  - "workflow_call"

env:
  RUFF_OUTPUT_FORMAT: "github"
  UV_FROZEN: 1
  PREK_SKIP: "pytest"

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v7"
        with:
          enable-cache: true
          cache-python: true

      - name: "Install Python dependencies"
        run: "uv sync --group dev"

      - name: "Install Node dependencies"
        run: "npm install"

      - name: "Lint"
        uses: "j178/prek-action@v2.0.4"
        with:
          extra-args: "--all-files"
