---
name: "Lint"

on: # yamllint disable-line rule:truthy
  - "workflow_call"

env:
  RUFF_OUTPUT_FORMAT: "github"
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v7"
        with:
          enable-cache: true
          cache-python: true

      - name: "Install Python dependencies"
        run: "uv sync --group dev"

      - name: "Set up Node"
        uses: "actions/setup-node@v6"
        with:
          node-version: 24
          cache: "yarn"

      - name: "Install Node dependencies"
        run: "yarn install --frozen-lockfile"

      - name: "Lint"
        uses: "j178/prek-action@v2.0.2"
        with:
          extra-args: "--all-files --skip pytest"
