---
name: "Test"

on: # yamllint disable-line rule:truthy
  - "workflow_call"

env:
  UV_FROZEN: 1

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v8"
        with:
          enable-cache: true
          cache-python: true

      - name: "Install Python dependencies"
        run: "uv sync --group dev"

      - name: "Install system dependencies"
        run: "sudo apt-get install --no-install-recommends -y libmagic1"

      - name: "Test"
        run: "uv run pytest"
